language: node_js
node_js:
  - "8.0.0"
  
services:
  - postgresql

addons:
    postgresql: '9.6'


env:
  - DATABASE_URL='postgresql://postgres@localhost:5432/waiterApp';


before_script:
  
  - psql -c 'create database waiterApp;' -U postgres
  - psql -U postgres -d waiterApp -a -f database.sql
